#!/bin/bash
APPTAINER_ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
set -e

mode=$1 # exec or shell

directories=("/cvmfs" "/exp" "/nashome" "/opt" "/run/user" "/etc/hostname" "/etc/hosts" "/etc/krb5.conf" "/home" "/pnfs/dune" "/data/dune/")

mounts=""

for d in ${directories[@]}
do
    if [ -d "$d" ] || [ -f "$d" ]; then
        mounts+="$d," 
    fi
done
mounts=`echo $mounts | rev | cut -c2- | rev`

echo $mounts

if [[ "$mode" == "shell" ]]; then
    /cvmfs/oasis.opensciencegrid.org/mis/apptainer/current/bin/apptainer shell --shell=/bin/bash -B $mounts --env "APPTAINER_ROOT=$APPTAINER_ROOT" --ipc --pid /cvmfs/singularity.opensciencegrid.org/fermilab/fnal-dev-sl7:latest
elif [[ "$mode" == "exec" ]]; then
    if [ "$#" -eq 1 ]; then
        echo "you need to pass a command when running with 'exec'"
    else
        /cvmfs/oasis.opensciencegrid.org/mis/apptainer/current/bin/apptainer exec -B $mounts --env "APPTAINER_ROOT=$APPTAINER_ROOT" --ipc --pid /cvmfs/singularity.opensciencegrid.org/fermilab/fnal-dev-sl7:latest $2
    fi
else
    echo "$1 not a valid way to start a container, choose 'exec' or 'shell'"
fi
