#!/bin/bash
set -e
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo $SCRIPT_DIR

container exec ./install_miniforge.sh
container exec ./create_dunesw.sh
./create_analysis_area.sh # install python analysis code
